version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.13.15
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
    - 4.2.16
  - dependency-name: ioredis
    versions:
    - 4.19.4
    - 4.22.0
    - 4.24.5
    - 4.25.0
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.8.0
    - 7.0.0
  - dependency-name: "@sentry/node"
    versions:
    - 6.0.2
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.2
    - 6.2.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.3
    - 5.2.0
  - dependency-name: simple-icons
    versions:
    - 4.10.0
    - 4.11.0
    - 4.14.0
    - 4.15.0
    - 4.16.0
    - 4.8.0
    - 4.9.0
  - dependency-name: "@babel/register"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.13.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.3
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.11
    - 2.32.4
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.3.3
    - 31.6.0
    - 32.0.0
    - 32.2.0
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
  - dependency-name: babel-plugin-inline-react-svg
    versions:
    - 1.1.2
    - 2.0.0
  - dependency-name: danger
    versions:
    - 10.6.0
    - 10.6.1
    - 10.6.2
  - dependency-name: "@types/react-select"
    versions:
    - 3.1.2
    - 4.0.13
  - dependency-name: gatsby-plugin-page-creator
    versions:
    - 2.10.0
    - 2.9.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.21
    - 14.14.25
  - dependency-name: bl
    versions:
    - 4.0.3
    - 4.0.4
  - dependency-name: gatsby-plugin-remove-trailing-slashes
    versions:
    - 2.8.0
    - 2.9.0
  - dependency-name: gatsby-plugin-typescript
    versions:
    - 2.10.0
    - 2.11.0
  - dependency-name: start-server-and-test
    versions:
    - 1.11.7
    - 1.12.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 3.9.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-plugin-catch-links
    versions:
    - 2.9.0
  - dependency-name: react-select
    versions:
    - 4.0.2
  - dependency-name: sinon
    versions:
    - 9.2.3
  - dependency-name: fast-xml-parser
    versions:
    - 3.17.6
  - dependency-name: prom-client
    versions:
    - 13.0.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: pretty-bytes
    versions:
    - 5.5.0
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.7
  - dependency-name: eslint-plugin-sort-class-members
    versions:
    - 1.9.0
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: "@types/react-helmet"
    versions:
    - 6.1.0
  - dependency-name: xmldom
    versions:
    - 0.4.0
  - dependency-name: chai-datetime
    versions:
    - 1.7.0
  - dependency-name: config
    versions:
    - 3.3.3
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: nock
    versions:
    - 13.0.5
  - dependency-name: react-error-overlay
    versions:
    - 6.0.8
- package-ecosystem: npm
  directory: "/badge-maker"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 99
